targets:
  $default:
    builders:
      freezed:
        enabled: true
        options:
          # Generate copyWith method
          copyWith: true
          # Generate toJson/fromJson
          toJson: true
          fromJson: true
          # Generate equals and hashCode
          equal: true
          # Generate toString
          toString: true

      json_serializable:
        enabled: true
        options:
          any_map: false
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          ignore_unannotated: false
          include_if_null: true

      riverpod_generator:
        enabled: true

      hive_generator:
        enabled: true
