// Mocks generated by Mockito 5.4.6 from annotations
// in hydrate_or_die/test/presentation/screens/photo_validation/photo_validation_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:camera/camera.dart' as _i5;
import 'package:hydrate_or_die/core/services/camera_permission_service.dart'
    as _i2;
import 'package:hydrate_or_die/domain/use_cases/photo/capture_photo_use_case.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CameraPermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraPermissionService extends _i1.Mock
    implements _i2.CameraPermissionService {
  MockCameraPermissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.CameraPermissionStatus> checkPermissionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermissionStatus, []),
            returnValue: _i3.Future<_i2.CameraPermissionStatus>.value(
              _i2.CameraPermissionStatus.granted,
            ),
          )
          as _i3.Future<_i2.CameraPermissionStatus>);

  @override
  _i3.Future<_i2.CameraPermissionStatus> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i3.Future<_i2.CameraPermissionStatus>.value(
              _i2.CameraPermissionStatus.granted,
            ),
          )
          as _i3.Future<_i2.CameraPermissionStatus>);

  @override
  _i3.Future<bool> openSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openSettings, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> canRequestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#canRequestPermission, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [CapturePhotoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCapturePhotoUseCase extends _i1.Mock
    implements _i4.CapturePhotoUseCase {
  MockCapturePhotoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> call(_i5.CameraController? cameraController) =>
      (super.noSuchMethod(
            Invocation.method(#call, [cameraController]),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#call, [cameraController]),
              ),
            ),
          )
          as _i3.Future<String>);
}
