// Mocks generated by Mockito 5.4.6 from annotations
// in hydrate_or_die/test/presentation/screens/avatar_selection/avatar_selection_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hydrate_or_die/domain/entities/avatar.dart' as _i4;
import 'package:hydrate_or_die/domain/entities/avatar_state.dart' as _i5;
import 'package:hydrate_or_die/domain/repositories/avatar_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AvatarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAvatarRepository extends _i1.Mock implements _i2.AvatarRepository {
  MockAvatarRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Avatar?> getAvatar() =>
      (super.noSuchMethod(
            Invocation.method(#getAvatar, []),
            returnValue: _i3.Future<_i4.Avatar?>.value(),
          )
          as _i3.Future<_i4.Avatar?>);

  @override
  _i3.Future<void> saveSelectedAvatar(String? avatarId) =>
      (super.noSuchMethod(
            Invocation.method(#saveSelectedAvatar, [avatarId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateAvatarState(_i5.AvatarState? state) =>
      (super.noSuchMethod(
            Invocation.method(#updateAvatarState, [state]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLastDrinkTime(DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastDrinkTime, [timestamp]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<DateTime?> getLastDrinkTime() =>
      (super.noSuchMethod(
            Invocation.method(#getLastDrinkTime, []),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<DateTime?> getDeathTime() =>
      (super.noSuchMethod(
            Invocation.method(#getDeathTime, []),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<void> updateDeathTime(DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeathTime, [timestamp]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
