// Mocks generated by Mockito 5.4.6 from annotations
// in hydrate_or_die/test/data/repositories/avatar_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hydrate_or_die/data/data_sources/local/avatar_local_data_source.dart'
    as _i2;
import 'package:hydrate_or_die/data/models/avatar_dto.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AvatarLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAvatarLocalDataSource extends _i1.Mock
    implements _i2.AvatarLocalDataSource {
  MockAvatarLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> getSelectedAvatarId() =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedAvatarId, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> saveSelectedAvatarId(String? avatarId) =>
      (super.noSuchMethod(
            Invocation.method(#saveSelectedAvatarId, [avatarId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.AvatarDto?> getAvatarState() =>
      (super.noSuchMethod(
            Invocation.method(#getAvatarState, []),
            returnValue: _i3.Future<_i4.AvatarDto?>.value(),
          )
          as _i3.Future<_i4.AvatarDto?>);

  @override
  _i3.Future<void> saveAvatarState(_i4.AvatarDto? avatarDto) =>
      (super.noSuchMethod(
            Invocation.method(#saveAvatarState, [avatarDto]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateAvatarStateField(String? state) =>
      (super.noSuchMethod(
            Invocation.method(#updateAvatarStateField, [state]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLastDrinkTime(DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastDrinkTime, [timestamp]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAvatarData() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAvatarData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
