// Mocks generated by Mockito 5.4.6 from annotations
// in hydrate_or_die/test/data/repositories/hydration_log_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hydrate_or_die/data/data_sources/local/hydration_log_local_data_source.dart'
    as _i2;
import 'package:hydrate_or_die/data/models/hydration_log_dto.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HydrationLogLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHydrationLogLocalDataSource extends _i1.Mock
    implements _i2.HydrationLogLocalDataSource {
  MockHydrationLogLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addLog(_i4.HydrationLogDto? logDto) =>
      (super.noSuchMethod(
            Invocation.method(#addLog, [logDto]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.HydrationLogDto>> getLogsForDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLogsForDateRange, [startDate, endDate]),
            returnValue: _i3.Future<List<_i4.HydrationLogDto>>.value(
              <_i4.HydrationLogDto>[],
            ),
          )
          as _i3.Future<List<_i4.HydrationLogDto>>);

  @override
  _i3.Future<double> getTotalVolumeForDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalVolumeForDateRange, [
              startDate,
              endDate,
            ]),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<int> deleteLogsOlderThan(DateTime? cutoffDate) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLogsOlderThan, [cutoffDate]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.HydrationLogDto>> getAllLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllLogs, []),
            returnValue: _i3.Future<List<_i4.HydrationLogDto>>.value(
              <_i4.HydrationLogDto>[],
            ),
          )
          as _i3.Future<List<_i4.HydrationLogDto>>);
}
