// Mocks generated by Mockito 5.4.6 from annotations
// in hydrate_or_die/test/domain/use_cases/hydration/record_hydration_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hydrate_or_die/domain/entities/avatar.dart' as _i8;
import 'package:hydrate_or_die/domain/entities/avatar_state.dart' as _i6;
import 'package:hydrate_or_die/domain/entities/hydration_log.dart' as _i4;
import 'package:hydrate_or_die/domain/entities/user.dart' as _i10;
import 'package:hydrate_or_die/domain/repositories/avatar_repository.dart'
    as _i7;
import 'package:hydrate_or_die/domain/repositories/hydration_log_repository.dart'
    as _i2;
import 'package:hydrate_or_die/domain/repositories/user_repository.dart' as _i9;
import 'package:hydrate_or_die/domain/use_cases/avatar/update_avatar_state_use_case.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HydrationLogRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHydrationLogRepository extends _i1.Mock
    implements _i2.HydrationLogRepository {
  MockHydrationLogRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addLog(_i4.HydrationLog? log) =>
      (super.noSuchMethod(
            Invocation.method(#addLog, [log]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.HydrationLog>> getLogsForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getLogsForDate, [date]),
            returnValue: _i3.Future<List<_i4.HydrationLog>>.value(
              <_i4.HydrationLog>[],
            ),
          )
          as _i3.Future<List<_i4.HydrationLog>>);

  @override
  _i3.Future<List<_i4.HydrationLog>> getTodayLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayLogs, []),
            returnValue: _i3.Future<List<_i4.HydrationLog>>.value(
              <_i4.HydrationLog>[],
            ),
          )
          as _i3.Future<List<_i4.HydrationLog>>);

  @override
  _i3.Future<double> getTotalVolumeForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalVolumeForDate, [date]),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<int> deleteOldLogs() =>
      (super.noSuchMethod(
            Invocation.method(#deleteOldLogs, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}

/// A class which mocks [UpdateAvatarStateUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateAvatarStateUseCase extends _i1.Mock
    implements _i5.UpdateAvatarStateUseCase {
  MockUpdateAvatarStateUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.AvatarState> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i3.Future<_i6.AvatarState>.value(
              _i6.AvatarState.fresh,
            ),
          )
          as _i3.Future<_i6.AvatarState>);
}

/// A class which mocks [AvatarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAvatarRepository extends _i1.Mock implements _i7.AvatarRepository {
  @override
  _i3.Future<_i8.Avatar?> getAvatar() =>
      (super.noSuchMethod(
            Invocation.method(#getAvatar, []),
            returnValue: _i3.Future<_i8.Avatar?>.value(),
            returnValueForMissingStub: _i3.Future<_i8.Avatar?>.value(),
          )
          as _i3.Future<_i8.Avatar?>);

  @override
  _i3.Future<void> saveSelectedAvatar(String? avatarId) =>
      (super.noSuchMethod(
            Invocation.method(#saveSelectedAvatar, [avatarId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateAvatarState(_i6.AvatarState? state) =>
      (super.noSuchMethod(
            Invocation.method(#updateAvatarState, [state]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLastDrinkTime(DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastDrinkTime, [timestamp]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<DateTime?> getLastDrinkTime() =>
      (super.noSuchMethod(
            Invocation.method(#getLastDrinkTime, []),
            returnValue: _i3.Future<DateTime?>.value(),
            returnValueForMissingStub: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<DateTime?> getDeathTime() =>
      (super.noSuchMethod(
            Invocation.method(#getDeathTime, []),
            returnValue: _i3.Future<DateTime?>.value(),
            returnValueForMissingStub: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<void> updateDeathTime(DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeathTime, [timestamp]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i9.UserRepository {
  @override
  _i3.Future<_i10.User?> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i3.Future<_i10.User?>.value(),
            returnValueForMissingStub: _i3.Future<_i10.User?>.value(),
          )
          as _i3.Future<_i10.User?>);

  @override
  _i3.Future<void> saveProfile(_i10.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfile, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateProfile(_i10.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProfile() =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> hasProfile() =>
      (super.noSuchMethod(
            Invocation.method(#hasProfile, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
