// Mocks generated by Mockito 5.4.6 from annotations
// in hydrate_or_die/test/presentation/screens/photo/glass_size_selection_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hydrate_or_die/domain/entities/glass_size.dart' as _i4;
import 'package:hydrate_or_die/domain/use_cases/hydration/record_hydration_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRecordHydrationResult_0 extends _i1.SmartFake
    implements _i2.RecordHydrationResult {
  _FakeRecordHydrationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecordHydrationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordHydrationUseCase extends _i1.Mock
    implements _i2.RecordHydrationUseCase {
  MockRecordHydrationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.RecordHydrationResult> call({
    required String? photoPath,
    required _i4.GlassSize? glassSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #photoPath: photoPath,
              #glassSize: glassSize,
            }),
            returnValue: _i3.Future<_i2.RecordHydrationResult>.value(
              _FakeRecordHydrationResult_0(
                this,
                Invocation.method(#call, [], {
                  #photoPath: photoPath,
                  #glassSize: glassSize,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.RecordHydrationResult>);
}
